### ISSUE TITLE
generating occurrences when when add_recurrence_time is used

### ISSUE THREAD

**Issue by sfusato** [peek-travel/cocktail#80]
Take this schedule for example to which I add two recurrence times. Then I use the last added recurrence time as the 2nd arg when calling `occurrences`, which should return the same one back since it's the last occurrence.
```
Cocktail.Schedule.new(~N[2015-01-08 18:30:00])
  |> Cocktail.Schedule.add_recurrence_rule(
    :daily,
    days: [:thursday, :friday, :wednesday],
    until: ~N[2015-01-14 18:30:00]
  )
  |> Cocktail.Schedule.add_recurrence_time(~N[2015-01-23 18:30:00])
  |> Cocktail.Schedule.add_recurrence_time(~N[2015-01-24 18:30:00])
  |> Cocktail.Schedule.occurrences(~N[2015-01-24 18:30:00])
```
expected result: `[~N[2015-01-24 18:30:00]]`
actual result: `[~N[2015-01-23 18:30:00], ~N[2015-01-24 18:30:00]]`

**Comment by doughsay** [comment]
thanks @sfusato, looks like a bug.  Not sure when I'll be able to get to it though...
